const express = require("express");
const jsonParser = express.json();
const app = express();
const mainController=require('./controllers/mainController');
const cookieParser = require('cookie-parser');
app.use(cookieParser());
app.use('/',express.static('./public/style'));
app.use('/',express.static('./public/script'));
app.post('/authentication',jsonParser,mainController.check);
app.get("/authentication", mainController.authentication);
app.post('/', jsonParser,mainController.start);
app.post("/config", jsonParser,mainController.config);
app.post("/renew", mainController.renew);
app.get("/", mainController.index);
app.get("/console",mainController.console);
app.post("/console",jsonParser,mainController.consoleRun);
app.get("/duplicate_identifiers",mainController.duplicate_identifiers);
app.post("/duplicate_identifiers",jsonParser,mainController.search);
app.get("/download*",mainController.download);
app.use(mainController.error);
app.listen(3000);